import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <div>
          <h1 className="flex justify-center m-5">TASK APP</h1>
          <hr></hr>
          <div className="flex justify-center grid grid-rows-2">
            {/* TODO:  NAV BAR */}
            {/* <NavigationMenu>
                <NavigationMenuList>
                  <NavigationMenuItem className="flex">
                    <NavigationMenuLink render={<Link href="/todo" />}>Home</NavigationMenuLink>
                    <NavigationMenuLink render={<Link href="/dashboard" />}>Dashboard</NavigationMenuLink>
                  </NavigationMenuItem>
                </NavigationMenuList>
              </NavigationMenu> */}
          </div>
        </div>
        <main>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
